---
title: "lending_Club"
author: "Huiting Sheng, Hua Zou, Lixin Wang"
date: "9/9/2020"
output: html_document
---

<<<<<<< HEAD
```{r import library}
packages=c("caret","ggplot2", "tidyverse", "dplyr", "corrplot")
## Now load or install&load all
package.check <- lapply(packages,FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)
```

```{r}
data=read.csv("LoanStats3a.csv", header=T)
data=as_tibble(data)
data
```
The original data dimension is `r dim(data)`. 

```{r split the data into X and Y}
X=select(data,-loan_status)
Y=select(data,loan_status) %>%unlist()
```

#### get data structure
```{r data structure}
str(data)
sapply(data,function(x) length(unique(x)))
```
quanlitive: term
numeric
suspicious
```{r clean data }
## get columns that doesn't have any info
emptycols=c()
for (i in 1:ncol(data)){
  if (all(is.na(data[,i]))) {
    emptycols=c(emptycols,colnames(data[,i]))
  }
}
emptycols
## remove the empty columns
df <- data %>%select(-emptycols)

str(df)


ggplot_missing = function(x) {
  if (!require(reshape2)) warning("you need to install reshape2")
  require(reshape2)
  x %>% is.na %>% melt
}


badaccount=df %>% filter((!loan_status %in% c("Fully Paid", "Current"))) %>% select(-c(pymnt_plan,url,initial_list_status,policy_code, application_type))

table(df$pub_rec)
filter(badcustom, loan_status=="Does not meet the credit policy. Status:Charged Off")$pymnt_plan
table(badcustom$next_pymnt_d)
```
pymnt_plan=="y" only one record, remove url, initial_list_status,policy_code, application_type
most charge off account out_prncp is 0
```{r}
state=as.table(table(df$addr_state))
ggplot(state) + geom_histogram()
```
=======
## Import Data
```{r import data}
data=read.csv("LoanStats3a.csv", heade=T)
head(data)
```

## Load in packages
```{r loadingPackages}
if(!require(tidyverse)){install.packages('tidyverse');require(tidyverse)}

if(!require(corrplot)){install.packages('corrplot');require(corrplot)}

if(!require(caret)){install.packages('caret');require(caret)}

if(!require(e1071)){install.packages('e1071');require(e1071)}

if(!require(reshape2)){install.packages('reshape2');require(reshape2)}
```

## Data cleaning and pre-processing

#### Select features of interest
```{r}
# check NAs in the dataset
str(data)

NAcol <- which(colSums(is.na(data))>0)
library(knitr) 
kable(sort(colSums(sapply(data[NAcol], is.na)),decreasing = T) )


# remove all empty columns
data = Filter(function(x)!all(is.na(x)), data)


# find the column with single value except for NA. 
data1 = data %>%
  drop_na() %>%
  select_if(~n_distinct(.) < 2)

sapply(data1, function(x){length((unique(x)))})


# remove some unimportant columns and columns with 1 levels besides NA.
sapply(data,function(x){ length(unique(x)) })

loanData = data %>%
  select(-id, -member_id, -issue_d, -url, -desc, -earliest_cr_line, -pub_rec_bankruptcies, -last_pymnt_d, -next_pymnt_d, -last_credit_pull_d, -application_type, -mths_since_last_delinq, -mths_since_last_record, -colnames(data1))

str(loanData)

# Check class of the loanData
table(sapply(loanData[1,],class))

sapply(loanData, function(x){ length(unique(x)) })
# ??? it looks like we have some numeric qualitative features.

``` 

#### Missing values
```{r missingvalues}
# check how many NAs in each feature of quantative features
sapply(loanData, FUN = function(x) sum(is.na(x)))

# check the rows with NAs
naData = loanData %>% filter_all(any_vars(is.na(.)))

# impute missing values with "preProcess"
require(RANN)

loandataImputeMedian = preProcess(loanData, method = 'medianImpute', k = 5)
loandataImpute = predict(loandataImputeMedian, loanData)
anyNA(loandataImpute)

# Check for numeric features, impute missing values
loandataImputeMedian = preProcess(loanDataQuant, method = 'medianImpute', k = 5)
loandataImpute = predict(loandataImputeMedian, loanDataQuant)
anyNA(loandataImpute)

# Correlation plot omit the missing data
dataNumCorr = cor(loandataImpute)
corrplot(dataNumCorr, order = "hclust", tl.cex = 0.35)

# remove the correlated features
highcorr = findCorrelation(dataNumCorr, 0.85, verbose=TRUE, names = TRUE)
segloandataImputeRemoveCorr = select(loandataImpute, -highcorr)
colnames(segloandataImputeRemoveCorr)

```

#### Skewness check
```{r}
skewed = apply(loanDataQuant,2,skewness)
skewed
>>>>>>> 456202f7a237cb3b6e0fade1fd9e7b7da8ef67fd

skewed = apply(loandataImpute,2,skewness)
skewed
```